### ISSUE TITLE
Problemas to make work.

### ISSUE THREAD

**Issue by portalthiago** [zarplata/zabbix-agent-extension-elasticsearch#2]
Hey Guys,
im sorry for ask but i really need help with this matter. After installing the packages and install go and move the .conf file from your .zip to the directory /zabbix/zabbix_agentd.d/.  Im stuck with this messages on latest data from zabbix:

"Usage:
  zabbix-agent-extension-elastic [options]"

and i dont understand properly this instructions here.

"Customize key prefix
It may you need if key in template already used.

If you need change key elasticsearch.* -> YOUR_PREFIX_PART.elasticsearch.*, run script custom_key_template.sh whit YOUR_PREFIX_PART and import updated zabbix template template_elasticsearch_service.xml.

./custom_key_template.sh YOUR_PREFIX_PART"

PLEASE! can u help-me understand?

**Comment by akitsul** [comment]
Hi,

I fixed zabbix template, please re-export template_elasticsearch_service.xml in Zabbix.

And check out the latest data for a host with linked our template in Zabbix.

**Comment by portalthiago** [comment]
Hi Akitsul,
i do what was proposed, and re-import the template, but the problem still there. Maybe i forgot how to configure some MACRO? My current configuration run as follow. Can u please put some light on it? What the meaning of "None_pfx" ?? 


![screen shot 2018-05-22 at 10 49 35](https://user-images.githubusercontent.com/20935653/40366807-66baba24-5dae-11e8-83ee-552cbdac077f.png)

**Comment by tears-of-noobs** [comment]
Hi @portalthiago. `None_pfx` its default value for item key name prefix generally you must not change it. If you have not change it your keys for items must look like that - `elasticsearch.cluster_health.active_primary_shards` but if you change it, for example to - `mysuperprefix` keys must look like - `mysuperprefix.elasticsearch.cluster_health.active_primary_shards`. So, if in current installation of zabbix you don't have anymore Elasticsearch templates - you must not change this macro. What about your problem, show me please history of `Elasticsearch get stats` item in latest data/
Show me content from user parameter configuration.
```sh
cat /path/to/zabbix_agentd.d/zabbix-agent-extension-elasticsearch.conf
```
 And try manually execute extension, like this
```sh
/usr/bin/zabbix-agent-extension-elasticsearch --zabbix-host YOUR_ZABBIX_IP --zabbix-prefix None_pfx
```
